// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Pose.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _GEOMETRY_MSGS_POSE_STAMPED_HPP_
#define _GEOMETRY_MSGS_POSE_STAMPED_HPP_


#include "../topic.hpp"

#include "../std_msgs/Header.hpp"
#include "../geometry_msgs/Pose.hpp"

namespace geometry_msgs {

class PoseStamped : public ros2udds::Topic<PoseStamped>
{
public:
  std_msgs::Header header;
  geometry_msgs::Pose pose;

  PoseStamped():
    Topic("geometry_msgs::msg::dds_::PoseStamped_", "PoseStamped", GEOMETRY_MSGS_POSE_STAMPED_ID),
    header(),
    pose()
  {}


  bool serialize(ucdrBuffer* msg_buf, const PoseStamped* topic)
  {
    ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
    (void) header.serialize(writer, &topic->header);
    (void) pose.serialize(writer, &topic->pose);

    return !writer->error;
  }

  bool deserialize(ucdrBuffer* msg_buf, PoseStamped* topic)
  {
    ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
    (void) header.deserialize(reader, &topic->header);
    (void) pose.deserialize(reader, &topic->pose);

    return !reader->error;
  }

  uint32_t size_of_topic(const PoseStamped* topic, uint32_t size)
  {
    uint32_t previousSize = size; 
    size += header.size_of_topic(&topic->header, size); // KURWA MAC!!!
    size += pose.size_of_topic(&topic->pose, size);
    
    return size - previousSize;
  }

};

} // namespace geometry_msgs


#endif // _GEOMETRY_MSGS_POSE_STAMPED_HPP_
